[versions]
agp = "8.7.3"
kotlin = "2.1.0"
serialization = "1.7.3"
composeBom = "2024.11.00"
compose = "1.7.6"
compose-material3 = "1.3.1"
compose-navigation = "2.7.5"
compose-shapes = "1.0.0-rc01"
androidx-activityCompose = "1.10.0"
sqldelight = "2.0.2"
date-time = "0.4.0"
koin = "4.1.0-Beta5"
stately-common = "1.2.0"
datastore = "2.0.0-alpha02"


[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "compose-navigation" }
compose-shapes = { module = "androidx.graphics:graphics-shapes", version.ref = "compose-shapes" }

sqldelight-driver-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-driver-native = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
sqldelight-driver-jvm = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
sqldelight-async = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-viewModel = { module = "io.insert-koin:koin-core-viewmodel", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }

datastore = { module = "de.charlex.settings:settings-datastore", version.ref = "datastore" }

datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "date-time" }
stately-common = { module = "co.touchlab:stately-common", version.ref = "stately-common" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
sqldelight-driver = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
